#Created By: Jared Fowler
#Makes comp322Lab1.c

program:
	@echo "Making Sense of Ones and Zeros By: Jared Fowler"
	cc comp322Lab0.c -o zero-one
	@echo " "
	@echo "To Run:	 <stdin> | ./zero-one    or    ./zero-one <inputFile>" 
	@echo " "
	@echo "Examples:  echo 1101010101 | ./zero-one"
	@echo "           cat <inputFile> | ./zero-one"
	@echo "           ./zero-one <inputFile>"
	@echo " "
